language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: kx8HCgqjp7w0CWu5/udMB4QlmWbjfEuQJcE/vU0tYbK83ebfgjGAjrdxQZb+rthGg/+/Pm1PWsppLcYL08RvbNVKHjq2OWjFd7P77nukXvkWB+JtIy7eBRY7nXFH2NZoANpdPXZOilLoHiUbAm5P5Pbsua/TGBN4JbtRyk9wEJBm7vWgR1qIURXv+mrn0UInqaJuSXQcFc0lEZeZ/Uuab+VIuua/LG30wIfkn8tqj6xBDWSbJpGX0qENPPj5GFI7pEXdz4XmlWPMmjJ/7eDhu0G6IMvhmguozWdFo0l3900DpnxVgkf/4p3RB+qhNvZFeL4gQrVZeX2NP9bw7JkMdUSvTqjb2s5DvFXY4Yl1ShBDZI/Uv4Bwg9ytXAnQxjhMXCeiA05Z9BiXqjdAq2eadmoELUK1Q7hLalBcIMV+QqJ4xURKOYMa+gisH+GPrboLxQ+V0eoACb+n8Q6V4mf7MdVlTyRzQsNUcRgigsdyT/6hsk5DVs20xDjDHMeGRxI8JCwnDqYIUwuYFM7Q9nsj1tOSw3IHwRaXodTC36v7/R9HdqjzVc0Gv0R4wj8mQxVhLUsyEI+JYSO9ZkSWY+n5+8HIOhV2Kvd49GCgsVS5JZdDIj3LUxrGDYDahmk1c1wpO5m8ye41i5Nd1m8g2E8CPSXcx4rns0Gm7omdffNJj5Y=
  - secure: a/fjkPU0NMMSFe6OKRmqyGC19AkLJBJBhxXlc1F51IeS5CNKXwowtNxdBwz67kNkBdpcOVuVsh+lvu1kO0wW7Mim/Q9nD1QLolPpI2laWHRWbz003j62qv1S9ryePe0pNQblci0Q4PaFTL0HSMi3AlUYdojwlQvpZ2WtZgqXikhwSZbpXJizvuvZ7WQyA6hEyrTOtiwdwC7IAR9snmaUX0lFWJh/6ck44yPDGlfzspiRNB28jxv6NDvnE26NqZFOhRwWWn8xpMn0SJrigD1MpJuf5slzQmPHaVyybTjglolTMgKQnHB6KVEqSOHC+GXTNm6ne5tlzeFDqafTET7S0fPXGO9FHxBB9HiAlAe55b/ESHhE+odA0oIHFKypn4IDox8zn+k2BRXqkFlM23UQN9xhCaQ0PbrckifcxIATwnjtc+/5+Jxlpl8Sgvqaeixl77RsuV1S+UcAKOOQbFVWm63b9bmZpz4Iwruo2as1RDMpwaVydTll9zh2Ssbeyy+RRgjasO9bDd9wqPf7Eo7A6nWSAaLBsrxmFohvSjmWN5z0zPUWzgOYbLzjRtbTewg4iQPpnOXgCASAVqPHmG3O/cBaJeA+gp5TXIGB7e0EHt8Nc398dPHmp8jkZNUAcY6zeQGr69AobYlJgBLfWBbYLq7dQgEyohC87TluSqup/AY=
