language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: kx8HCgqjp7w0CWu5/udMB4QlmWbjfEuQJcE/vU0tYbK83ebfgjGAjrdxQZb+rthGg/+/Pm1PWsppLcYL08RvbNVKHjq2OWjFd7P77nukXvkWB+JtIy7eBRY7nXFH2NZoANpdPXZOilLoHiUbAm5P5Pbsua/TGBN4JbtRyk9wEJBm7vWgR1qIURXv+mrn0UInqaJuSXQcFc0lEZeZ/Uuab+VIuua/LG30wIfkn8tqj6xBDWSbJpGX0qENPPj5GFI7pEXdz4XmlWPMmjJ/7eDhu0G6IMvhmguozWdFo0l3900DpnxVgkf/4p3RB+qhNvZFeL4gQrVZeX2NP9bw7JkMdUSvTqjb2s5DvFXY4Yl1ShBDZI/Uv4Bwg9ytXAnQxjhMXCeiA05Z9BiXqjdAq2eadmoELUK1Q7hLalBcIMV+QqJ4xURKOYMa+gisH+GPrboLxQ+V0eoACb+n8Q6V4mf7MdVlTyRzQsNUcRgigsdyT/6hsk5DVs20xDjDHMeGRxI8JCwnDqYIUwuYFM7Q9nsj1tOSw3IHwRaXodTC36v7/R9HdqjzVc0Gv0R4wj8mQxVhLUsyEI+JYSO9ZkSWY+n5+8HIOhV2Kvd49GCgsVS5JZdDIj3LUxrGDYDahmk1c1wpO5m8ye41i5Nd1m8g2E8CPSXcx4rns0Gm7omdffNJj5Y=
