language: node_js
node_js:
- '8'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- npm run build
after_script:
- greenkeeper-lockfile-upload
- codecov
env:
  global:
  - secure: a/fjkPU0NMMSFe6OKRmqyGC19AkLJBJBhxXlc1F51IeS5CNKXwowtNxdBwz67kNkBdpcOVuVsh+lvu1kO0wW7Mim/Q9nD1QLolPpI2laWHRWbz003j62qv1S9ryePe0pNQblci0Q4PaFTL0HSMi3AlUYdojwlQvpZ2WtZgqXikhwSZbpXJizvuvZ7WQyA6hEyrTOtiwdwC7IAR9snmaUX0lFWJh/6ck44yPDGlfzspiRNB28jxv6NDvnE26NqZFOhRwWWn8xpMn0SJrigD1MpJuf5slzQmPHaVyybTjglolTMgKQnHB6KVEqSOHC+GXTNm6ne5tlzeFDqafTET7S0fPXGO9FHxBB9HiAlAe55b/ESHhE+odA0oIHFKypn4IDox8zn+k2BRXqkFlM23UQN9xhCaQ0PbrckifcxIATwnjtc+/5+Jxlpl8Sgvqaeixl77RsuV1S+UcAKOOQbFVWm63b9bmZpz4Iwruo2as1RDMpwaVydTll9zh2Ssbeyy+RRgjasO9bDd9wqPf7Eo7A6nWSAaLBsrxmFohvSjmWN5z0zPUWzgOYbLzjRtbTewg4iQPpnOXgCASAVqPHmG3O/cBaJeA+gp5TXIGB7e0EHt8Nc398dPHmp8jkZNUAcY6zeQGr69AobYlJgBLfWBbYLq7dQgEyohC87TluSqup/AY=
  - secure: ZJEBQvf38kHfcCG37DmH37y2Pz1b/ApWR3PHj//xfzu5diug0fJKEVAzuLUWxguRLBbVjwUdKLVpWL9YvMm3ibBiHp8hKE7nHnxl9L1pznvfBG61FODCet8oYRcnZBLoxSdhJS9BoNk8Wrtn0O8BgOuZqIVlIsVQzA2uHnqxbbWdeUPhUa99LmZHTxr8BSzDaFf596ScIyOXYB50W2yg/tDSLBVMTQAxKVN3uPoTZx76aiEeq5wftD7HeBamkRxEZ5fKObC7zPXmTRMeTQ76OMvwiUgg1QvPP9PKPwNBA/othL4OwJZ1pDF33HtCMZJx/HeXNWqVsnE2BuNoOQsCdHyWiyHeOa8CZv+6MPwInldoeyaSkijHvla72XEd3E8CfS6PM9Hprahk3amvgAVLbDsv3Y8vOC4Msv3jahYJ5tLQS+RwpDH1Z3gmmO77U2SsLrEAR0Rt+Xra7LRek3atHjEE4TqWgc6BY/NxSNVB/Hqys/7/cLxV4ywCN9GggKh3asL5zpuQrH+qUI6OJ2khm7H3XZd2YlpdZVGZK/z3aV+/bLySp5mT7/qSrzppfF/tiKAt1CHOmJZGHFhFWeNuUGjufWzdZzZ9XoH9uanRs25zFFkUzabpDA4tVSodrHDX/j2ktQrlARFFQqP47ThlNgqqCuUQ70s8ctjFf5zn0Kk=
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run _version
    on:
      branch: master
      repo: smockle/periodic
      tags: false
  - provider: npm
    skip_cleanup: true
    email: bot@smockle.com
    api_key:
      secure: nq49OzaUpGbaoebFDbKxq5/FzbDuKwvn5ETfCpl5StWM/d6UFoGxkx+MnYI15wN2EzMcLT9ssRbCqQ5oD8U1lH6S5au4h3AARK2RuwBSZFDz158MdxltNgfL4Jsi1uDLlA4tmtrfKCTnu6Pdzb6OAVJlzUMI8ayEQuCtBbM90KyZLAgk2qqh2FdhE5hZh3vv+BGjEpRBCS88CXsCsApFxVLvF6DCkdotO5cPsCCxTa6yvR7HK3LvCnxhWPiYIiuJmANI7eo36VcIUEBRo3HFN5tNgBdpZu0NErtIGjzXV2AJzJhteUqnD+QywtCoQM3AE9GwDjNVOsvp3gPf3hPyKfZ+pGDT/zXyac4m+ABtXIHiYm9yw6Gr3gwmvl3VENQs9oUQttIRw2dVWHXQGe4x84dIuW5jPsQFXLnh21LH0hBXf06plC4kBv/1EG/zanycMLwOJfWNqGOmmjhAIV26+WBMJbJR/qF4KfBare2KgnG+7zn7k5cj3GbiPSKCVdF6wey4e8rbJcfqHvW5YTKj0Fu0/2sZ56UkM8Iw3oIrsakv+ouryZrKLnGkVLHTThA5GkHrLIfmFlD8BFsEq7bCH1l+20Rf42Sj1CbKFGffK34j+s6i1wSNNWoriujlPz5DoJbNw5ceDxfd3z6YjIn1ffkM+byYx7jjU1BAP79NgCk=
    on:
      branch: master
      repo: smockle/periodic
      tags: false
