// flow-typed signature: 0ffaf5b3e1c6e9bf99c43ae6a2114cc0
// flow-typed version: <<STUB>>/xlsx_v^0.10.4/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xlsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

 /*:: declare type Cell = {
   [string]: any,
   't': 'b' | 'n' | 'e' | 's' | 'd',
   'v': any
 }
 */

 /*:: declare type Worksheet = {
   [string]: Cell,
   '!ref': string
 }
 */

 /*:: declare type Workbook = {
   [string]: any,
   SheetNames: Array<string>,
   Sheets: {[string]: Worksheet}
 };
 */

 /*:: declare module 'xlsx' {
   declare module.exports: {
     readFile(filename: string, options?: any): Workbook,
     writeFile(workbook: Workbook, filename: string, options?: any): void,
     utils: {
       sheet_to_json(sheet: Worksheet, opts?: ?any): Array<{[string]: any}>
     }
   };
 }
 */
