// flow-typed signature: 437f767adfe6cfba2f8491e040a4ce59
// flow-typed version: <<STUB>>/xlsx_v^0.9.7/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xlsx'
 *
 * Fill this stub out by replacing all the `any` types.
 */

/*:: declare type Cell = {
  [string]: any,
  't': 'b' | 'n' | 'e' | 's' | 'd',
  'v': any
}
*/

/*:: declare type Worksheet = {
  [string]: Cell,
  '!ref': string
}
*/

/*:: declare type Workbook = {
  [string]: any,
  SheetNames: Array<string>,
  Sheets: {[string]: Worksheet}
};
*/

/*:: declare module 'xlsx' {
  declare module.exports: {
    readFile(filename: string, options?: any): Workbook,
    writeFile(workbook: Workbook, filename: string, options?: any): void,
    utils: {
      sheet_to_json(sheet: Worksheet, opts?: ?any): Array<{[string]: any}>
    }
  };
}
*/
